app = "zdv-training-scheduler"
primary_region = "lax"

[build]

[env]
  ZDV_OAUTH_AUTHORIZE_ENDPOINT = "oauth/authorize"
  ZDV_OAUTH_BASE_URL = "https://auth.zdvartcc.org/"
  ZDV_OAUTH_SCOPES = "['full_name vatsim_details']"
  ZDV_OAUTH_TOKEN_ENDPOINT = "oauth/token"
  ZDV_OAUTH_USER_INFO_URI = "https://auth.zdvartcc.org/v1/info"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
