jwtSecret = ""
discordSecret = ""

[oauth]

clientId = ""
clientSecret = ""
baseUrl = ""
authorizeEndpoint = ""
tokenEndpoint = ""
redirectUri = ""
userInfoUri = ""
userRoster = ""

[email]

host = ""
servername = ""
port = 0
user = ""
password = ""
from = ""
